### ISSUE TITLE
Bug with actions/checkout

### ISSUE THREAD

**Issue by crusaderky** [airspeed-velocity/asv#1508]
`asv run --python=same --set-commit-hash XXX` fails inside `actions/checkout` for pull requests, with the error message

> Unknown branch main in configuration

This is because, rightfully, `actions/checkout` does not download the main branch; only the current branch for the PR.

# Reproducer
```yaml
name: Benchmarks
on: [push, pull_request]
jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get the non-merge commit for PRs
          fetch-tags: true

      # snip: deploy python environment

      - run: |
          asv machine --yes
          asv run --python=same --quick --set-commit-hash $(git rev-parse HEAD)

      - uses: actions/upload-artifact@v4
        with:
          name: asv-results
          path: .asv/results
```
# Local reproducer
To reproduce locally, in asv.conf.json set

```json
    "branches": ["not-exist"],
```

# Expected behaviour
`asv --set-commit-hash` does not need to know about branches other than the one that contain the selected commit.

# Workarounds

1. Don't save results
```yaml
      - name: Run Benchmarks
        run: |
          asv machine --yes
          asv run --python=same --quick
```
2. Hack the config
```yaml

      - name: Run Benchmarks
        run: |
          sed -i "s/main/$(git rev-parse --abbrev-ref HEAD)/" asv.conf.json
          asv machine --yes
          asv run --python=same --quick --set-commit-hash $(git rev-parse HEAD)
```
